---

# Install Additional Apps & Remove Uneeded Ones
- include: modify_apps.yml

# Setup & Configure the Zabbix Agent
- include: setup_zabbixagent.yml

# Setup Users & Their Configurations
- include: users/main.yml

- name: Configure the KDM Login Manager
  lineinfile: dest=/etc/kde4/kdm/kdmrc regexp="{{ item.regexp }}" line="{{ item.line }}"
  with_items:
    - { regexp: '^#?AutoLoginEnable=',  line: 'AutoLoginEnable=true' }
    - { regexp: '^#?AutoLoginUser=',    line: 'AutoLoginUser=sese' }
    - { regexp: '^#?AutoLoginDelay=',   line: 'AutoLoginDelay=5' }
    - { regexp: '^#?PreselectUser=',   line: 'PreselectUser=Default' }
    - { regexp: '^DefaultUser=',      line: 'DefaultUser=sese' }
    - { regexp: '^#?UserList=',        line: 'UserList=true' }
    - { regexp: '^#?NumLock=',         line: 'NumLock=On' }
  tags: kdm
