---

- name: Ensure Base Applications are Installed
  apt:  name={{ item }} state=present install_recommends=yes
  with_items:
    - alsa-base
    - alsa-utils
    - anacron
    - avahi-daemon
    - eject
    - firmware-linux
    - hddtemp
    - iw
    - libgl1-mesa-dri
    - libnss-mdns
    - p7zip-full
    - pm-utils
    - sudo
    - udisks
    - unattended-upgrades
    - upower
    - xdg-user-dirs
    - xdg-utils
    - xorg
  sudo: yes
  tags: apps

# Built from `kde-full` backwards, eliminating uneccesary apps
- name: Ensure KDE Applications are Installed
  apt:  name={{ item }} state=present install_recommends=yes
  with_items:
    - kdm
    - polkit-kde-1
    - kde-plasma-desktop
    - kdeaccessibility
    - kdeadmin
    - kdeartwork
    - kdeedu
    - kdegames
    - kdegraphics
    - kdegraphics-strigi-analyzer
    - kdegraphics-thumbnailers
    - kdegraphics
    - svgpart
    - ffmpegthumbs
    - kio-audiocd
    - kmix
    - kscd
    - kde-config-cddb
    - kdenetwork
    - kdenetwork-filesharing
    - kde-zeroconf
    - kdenetwork-strigi-analyzers
    - kdeutils
    - print-manager
    - kdeplasma-addons
    - plasma-widget-networkmanagement
    - plasma-widget-folderview
    - system-config-printer
    - baloo4
    - kate
    - k3b
    - kdesudo
  sudo: yes
  tags:
    - apps
    - kde

- name: Ensure Packages for Firefox-KDE Integration are Installed
  apt:  name={{ item }} state=present
  with_items:
    - kde-config-gtk-style
    - gtk2-engines-oxygen
    - gtk3-engines-oxygen
  sudo: yes
  tags:
    - apps
    - kde

- name: Ensure Internet Applications and Plugins are Installed
  apt:  name={{ item }} state=present
  with_items:
    - chromium
    - filezilla
    - flashplugin-nonfree
    - icedtea-plugin
    - iceweasel
    - mumble
    - pepperflashplugin-nonfree
  sudo: yes
  tags: apps

- name: Ensure LibreOffice is Installed
  apt:  name={{ item }} state=present
  with_items:
    - libreoffice
    - libreoffice-help-en-us
    - libreoffice-kde
    - libreoffice-pdfimport
    - mythes-en-us
    - hunspell-en-us
    - hyphen-en-us
  sudo: yes
  tags: apps

- name: Ensure Multimedia Codecs are Installed
  apt:  name={{ item }} state=present
  with_items:
    - gir1.2-gst-plugins-base-1.0
    - gstreamer1.0-fluendo-mp3
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-pulseaudio
    - libavcodec-extra
    - libgstreamer-interfaces-perl
    - libgstreamer-perl
  sudo: yes
  tags: apps

- name: Ensure Miscellaneous Applications and Utilities are Installed
  apt:  name={{ item }} state=present
  with_items:
    - tome
    - crawl-tiles
    - gimp
    - gimp-data-extras
    - sqlite3
    - tumbler
    - tumbler-plugins-extra
  sudo: yes
  tags: apps
