---

- include: setup_dependencies.yml

- include: setup_keystone.yml
  tags: keystone

- include: setup_projects.yml
  tags: projects

- include: setup_glance.yml
  tags: glance

- include: setup_nova.yml
  tags: nova

- include: setup_neutron.yml
  tags: neutron

- include: setup_horizon.yml
  tags: horizon

- include: setup_networks.yml
  tags: networks
