---

- name: Ensure MongoDB is Installed
  apt: name={{ item }}
  become: yes
  with_items:
    - mongodb-server
    - mongodb-clients
    - python-pymongo

- name: Ensure MongoDB is Correctly Configured
  lineinfile: dest=/etc/mongodb.conf regexp='bind_ip = .*'
              line='bind_ip = {{ management_ip }}'
  become: yes
  notify: restart mongodb

- name: Ensure the RabbitMQ Apt Key is Installed
  apt_key:
    id: 0A9AF2115F4687BD29803A206B73A36E6026DFCA
    keyserver: hkps://keys.openpgp.org
  become: yes

- name: Ensure the RabbitMQ Apt Repositories are Configured
  apt_repository:
    repo: "deb {{ item }}"
    filename: rabbitmq
  with_items:
    - http://dl.bintray.com/rabbitmq-erlang/debian bionic erlang
    - http://dl.bintray.com/rabbitmq/debian bionic main
  become: yes

- name: Ensure RabbitMQ is Installed
  apt: name=rabbitmq-server
  become: yes

- name: Ensure the RabbitMQ Cookie is Installed Correctly
  copy: dest=/var/lib/rabbitmq/.erlang.cookie content="{{ vaulted_mq_cookie }}"
        owner=rabbitmq group=rabbitmq mode="400"
  become: yes
  notify: restart rabbitmq
  tags: ha

- meta: flush_handlers

- name: Add the RabbitMQ User
  rabbitmq_user: user={{ mq_user }} password={{ vaulted_mq_password }} vhost=/
                 configure_priv=.* read_priv=.* write_priv=.*
  become: yes
  become_user: rabbitmq

- name: Ensure Memcached is Installed
  apt: name={{ item }}
  become: yes
  with_items:
      - memcached
      - python-memcache

- name: Ensure Memcached is Correctly Configured
  lineinfile: dest=/etc/memcached.conf regexp='^-l .*$' state=present
              line='-l {{ management_ip }}'
  become: yes
  notify: restart memcached

- name: Ensure APCUPSd is Installed
  apt:
    name: apcupsd
  become: yes
  when: "'backup-controller' not in group_names"
  tags: ups

- name: Ensure APCUPSd is Configured
  lineinfile: dest=/etc/apcupsd/apcupsd.conf regexp="{{ item.regexp }}" line="{{ item.line }}"
  with_items:
    - regexp: "^DEVICE.*$"
      line: "DEVICE"
    - regexp: "BATTERYLEVEL .*$"
      line: "BATTERYLEVEL 50"
    - regexp: "MINUTES .*$"
      line: "MINUTES 15"
  become: yes
  notify: restart apcupsd
  when: "'backup-controller' not in group_names"
  tags: ups

- name: Ensure the APCUPSd Shutdown Script Exists
  copy:
    src: cluster-shutdown.sh
    dest: /etc/apcupsd/doshutdown
    mode: u=rwx,g=wrx,o=r
  become: yes
  when: "'backup-controller' not in group_names"
  tags: ups


- meta: flush_handlers
