---

- name: Ensure MongoDB is Installed
  apt: name={{ item }}
  become: yes
  with_items:
    - mongodb-server
    - mongodb-clients
    - python-pymongo

- name: Ensure MongoDB is Correctly Configured
  lineinfile: dest=/etc/mongodb.conf regexp='bind_ip = .*'
              line='bind_ip = {{ management_ip }}'
  become: yes
  notify: restart mongodb

- name: Ensure RabbitMQ is Installed
  apt: name=rabbitmq-server
  become: yes

- name: Ensure the RabbitMQ Cookie is Installed Correctly
  copy: dest=/var/lib/rabbitmq/.erlang.cookie content="{{ vaulted_mq_cookie }}"
        owner=rabbitmq group=rabbitmq mode="400"
  become: yes
  notify: restart rabbitmq
  tags: ha

- meta: flush_handlers

- name: Add the RabbitMQ User
  rabbitmq_user: user={{ mq_user }} password={{ vaulted_mq_password }} vhost=/
                 configure_priv=.* read_priv=.* write_priv=.*
  become: yes
  become_user: rabbitmq

- name: Ensure Memcached is Installed
  apt: name={{ item }}
  become: yes
  with_items:
      - memcached
      - python-memcache

- name: Ensure Memcached is Correctly Configured
  lineinfile: dest=/etc/memcached.conf regexp='^-l .*$' state=present
              line='-l {{ management_ip }}'
  become: yes
  notify: restart memcached
