---

- name: Ensure Keystone Database Exists
  mysql_db: name={{ keystone_db_name }}
            login_user=root login_password="{{ vaulted_db_root_password }}"
  when: inventory_hostname in groups['master-controller']
  notify:
    - sync keystone database
    - initialize key repositories
  become: yes

- name: Ensure the Keystone Database User Exists
  mysql_user: name={{ keystone_db_user }} password={{ vaulted_db_password }}
              priv='{{ keystone_db_name }}.*:ALL' host="{{ item }}"
              login_user=root login_password="{{ vaulted_db_root_password }}"
  with_items:
    - localhost
    - '%'
  when: inventory_hostname in groups['master-controller']
  become: yes

- name: Ensure Keystone is Installed
  apt: name={{ item }}
  become: yes
  with_items:
      - keystone
      - python-keystoneclient
      - apache2
      - libapache2-mod-wsgi-py3

- name: Ensure the Fernet Key Directory Exists
  file: path=/etc/keystone/fernet-keys state=directory
        owner=keystone group=keystone mode=700
  become: yes

- name: Ensure the Fernet Keys Exist
  copy: dest="/etc/keystone/fernet-keys/{{ item.file }}" content="{{ item.value }}"
        owner=keystone group=keystone mode=600 directory_mode=700
  with_items:
    - { file: "0", value: "{{ vaulted_fernet_key_0 }}" }
    - { file: "1", value: "{{ vaulted_fernet_key_1 }}" }
  become: yes

- name: Ensure Keystone is Correctly Configured
  ini_file: dest=/etc/keystone/keystone.conf section="{{ item.section }}"
            option="{{ item.option }}" value="{{ item.value }}"
  become: yes
  with_items:
    - { section: 'DEFAULT', option: 'bind_host', value: '{{ management_ip }}' }
    - { section: 'DEFAULT', option: 'public_bind_host', value: '{{ management_ip }}' }
    - { section: 'DEFAULT', option: 'admin_bind_host', value: '{{ management_ip }}' }
    - { section: 'database', option: 'connection',
        value: 'mysql+pymysql://{{ keystone_db_user }}:{{ vaulted_db_password }}@{{ ansible_hostname }}/{{ keystone_db_name }}' }
    - { section: 'token', option: 'provider', value: 'fernet' }
  notify:
    - sync keystone database
    - initialize key repositories
    - restart apache

- name: Ensure Apache is Correctly Configured
  lineinfile: dest=/etc/apache2/apache2.conf
              regexp='^ServerName .*' line='ServerName {{ master_controller_hostname }}'
  become: yes
  notify: restart apache

- name: Ensure Apache Does Not Listen on Port 80
  lineinfile: dest=/etc/apache2/ports.conf
              regexp='^Listen .*$' line='Listen {{ management_ip }}:80'
  become: yes
  notify: restart apache

- name: Ensure the Default Apache Site is Disabled
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  become: yes
  notify: restart apache

- name: Ensure Keystone Virtual Host is Correctly Configured
  template: src=apache-keystone.conf.j2 dest=/etc/apache2/sites-available/keystone.conf
  become: yes
  notify: restart apache

- name: Ensure the Keystone Virtual Host is Enabled
  file: src=/etc/apache2/sites-available/keystone.conf
        dest=/etc/apache2/sites-enabled/keystone.conf state=link
  become: yes
  notify: restart apache

- name: Ensure Default Keystone Database is Removed
  file: state=absent path=/var/lib/keystone/keystone.db
  become: yes

- meta: flush_handlers

- name: Bootstrap the OpenStack Identity Service & Endpoints
  shell: keystone-manage bootstrap --bootstrap-password {{ vaulted_admin_token }}
         --bootstrap-admin-url http://{{ master_controller_hostname }}:35357/v3
         --bootstrap-internal-url http://{{ master_controller_hostname }}:35357/v3
         --bootstrap-public-url http://{{ master_controller_hostname }}:5000/v3
         --bootstrap-region-id RegionOne
  become: yes
  when: inventory_hostname in groups['master-controller']
