---

- name: Ensure PostgreSQL is Installed
  apt: name={{ item }}
  become: yes
  with_items:
    - postgresql
    - python-psycopg2

- name: Ensure PostgreSQL Is Served on the Management Interface
  lineinfile: dest=/etc/postgresql/9.5/main/postgresql.conf
              regexp='.*listen_addresses =.*' line="listen_addresses = 'localhost,{{ management_ip }}'"
  become: yes
  notify: restart postgresql

- name: Ensure PostgreSQL Allows Connections from the Mangement Interface
  lineinfile: dest=/etc/postgresql/9.5/main/pg_hba.conf
              regexp='.*{{ management_network_cidr }}.*'
              line='host all all {{ management_network_cidr }} md5'
  become: yes
  notify: restart postgresql

- name: Ensure MongoDB is Installed
  apt: name={{ item }}
  become: yes
  with_items:
    - mongodb-server
    - mongodb-clients
    - python-pymongo

- name: Ensure MongoDB is Correctly Configured
  lineinfile: dest=/etc/mongodb.conf regexp='bind_ip = .*'
              line='bind_ip = {{ management_ip }}'
  become: yes
  notify: restart mongodb

- name: Ensure RabbitMQ is Installed
  apt: name=rabbitmq-server
  become: yes

- name: Add the RabbitMQ User
  rabbitmq_user: user={{ mq_user }} password={{ vaulted_mq_password }} vhost=/
                 configure_priv=.* read_priv=.* write_priv=.*
  become: yes

- name: Ensure Memcached is Installed
  apt: name={{ item }}
  become: yes
  with_items:
      - memcached
      - python-memcache

- name: Ensure Memcached is Correctly Configured
  lineinfile: dest=/etc/memcached.conf regexp='^-l .*$' state=present
              line='-l {{ management_ip }}'
  become: yes
  notify: restart memcached
