---

- hosts:
    - controllers
    - compute
    - storage
  roles:
    - { name: common, tags: common }

- hosts:
    - master-controller
    - controllers
  roles:
    - { name: controller, tags: controller }
  environment: "{{ stack_env }}"

- hosts:
    - compute
  roles:
    - { name: compute, tags: compute }

- hosts:
    - storage
  roles:
    - { name: storage, tags: storage }
