---

cinder_config:
  - { section: 'DEFAULT', option: 'enabled_backends', value: 'ceph' }
  - { section: 'DEFAULT', option: 'glance_api_servers', value: '{{ master_controller_hostname }}:9292' }
  - { section: 'database', option: 'connection',
      value: 'mysql+pymysql://{{ cinder_db_user }}:{{ vaulted_db_password }}@{{ master_controller_hostname }}/{{ cinder_db_name }}' }
  - { section: 'ceph', option: 'volume_driver',
      value: 'cinder.volume.drivers.rbd.RBDDriver' }
  - { section: 'ceph', option: 'volume_backend_name', value: 'ceph' }
  - { section: 'ceph', option: 'rbd_pool', value: 'volumes' }
  - { section: 'ceph', option: 'rbd_ceph_conf', value: '/etc/ceph/ceph.conf' }
  - { section: 'ceph', option: 'rbd_flatten_volume_from_snapshot', value: 'false' }
  - { section: 'ceph', option: 'rbd_max_clone_depth', value: '5' }
  - { section: 'ceph', option: 'rbd_store_chunk_size', value: '4' }
  - { section: 'ceph', option: 'rados_connect_timeout', value: '-1' }
  - { section: 'ceph', option: 'glance_api_version', value: '2' }
  - { section: 'ceph', option: 'rbd_user', value: 'cinder' }
  - { section: 'ceph', option: 'rbd_secret_uuid', value: '{{ vaulted_rbd_cinder_uuid }}' }
