---

- name:    restart zabbix_agent
  service: name=zabbix-agent state=restarted
  sudo:    yes

- name:    restart smbd
  service: name=smbd state=restarted
  sudo:    yes

- name:    restart nmbd
  service: name=nmbd state=restarted
  sudo:    yes

- name:    restart kdm
  service: name=kdm state=restarted
  sudo:    yes

- name:    restart cups
  service: name=cups state=restarted
  sudo:    yes

- name:    update package cache
  apt:     update_cache=yes
  sudo:    yes

- name:    update grub
  shell:   update-grub
  sudo:    yes

- name:    start unattended upgrades
  service: name=unattended-upgrades state=started
  sudo:    yes

- name:    restart network manager
  service: name=network-manager state=restarted
  sudo:    yes
