---

- name: Ensure Cinder is Installed
  apt: name=cinder-volume
  become: yes

- name: Ensure Cinder is Correctly Configured
  ini_file: dest=/etc/cinder/cinder.conf section="{{ item.section }}"
            option="{{ item.option }}" value="{{ item.value }}"
  become: yes
  with_items: "{{ common_auth_config + common_rabbit_config + common_cinder_config + cinder_config }}"
  notify:
    - restart tgt service
    - restart cinder service
