---

- name: Ensure Cinder & Dependencies are Installed
  apt: name={{ item }}
  become: yes
  with_items:
    - cinder-volume
    - mariadb-client
  tags: cinder

- name: Ensure Cinder is Correctly Configured
  ini_file: dest=/etc/cinder/cinder.conf section="{{ item.section }}"
            option="{{ item.option }}" value="{{ item.value }}"
  become: yes
  with_items: "{{ common_auth_config + common_rabbit_config + common_cinder_config + cinder_config }}"
  notify:
    - restart tgt service
    - restart cinder service
  tags:
    - cinder
    - ceph

- name: Ensure the Ceph Dependencies are Installed
  apt: name={{ item }}
  become: yes
  with_items:
    - python-rbd
    - ceph-common
  tags: ceph
