---

- name: Create the Hosts File
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' state=present
              line="{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']
  become: yes

- name: Ensure Package Cache is Current
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Ensure Chrony is Installed for NTP
  apt: name=chrony
  become: yes

- name: Ensure the the default NTP Servers are Removed
  replace: dest=/etc/chrony/chrony.conf
           regexp='^server .\.debian\.pool\.ntp\.org.*$' replace=""
  become: yes

- name: Ensure the Correct NTP Server is Set
  lineinfile: dest=/etc/chrony/chrony.conf regexp='^server .*$' state=present
              line="server {{ ntp }} iburst"
  notify: restart chrony
  become: yes

- name: Ensure the OpenStack Client is Installed
  apt: name=python-openstackclient
  become: yes
  #- name: Check if Reboot is Necessary
  #  stat: path=/var/run/reboot-required
  #  register: reboot-required
  #
  #- name: Reboot the System
  #  shell: reboot
  #  when: reboot-required.stat.exists
  #  become: yes
  #
  #- name: Wait for System Reboot
  #  local_action:
  #    module: wait_for
  #      host={{ ansible_ssh_host }} port={{ ansible_ssh_port }}
  #      delay=1 timeout=300
  #    become: no
  #    when: reboot-required.stat.exists
