---

- name: Create the Hosts File
  lineinfile: dest=/etc/hosts  regexp="{{ hostvars[item]['ansible_' + hostvars[item]['management_interface']]['ipv4']['address'] }}.*"
              line="{{ hostvars[item]['ansible_' + hostvars[item]['management_interface']]['ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}"
  with_items: "{{ groups['all'] }}"
  become: yes

- name: Ensure the Second Loopback Address is Removed from the Hosts File
  lineinfile: dest=/etc/hosts  regexp="127.0.1.1.*" state=absent
  become: yes

- name: Ensure the Master Controller is in the Hosts File
  lineinfile: dest=/etc/hosts regexp="{{ master_controller_ip }}.*"
              line="{{ master_controller_ip }} {{ master_controller_hostname }}"
  become: yes
  tags: ha

- name: Ensure Chrony is Installed for NTP
  apt: name=chrony
  become: yes

- name: Ensure the the default NTP Servers are Removed
  replace: dest=/etc/chrony/chrony.conf
           regexp='^(server|pool) .\.debian\.pool\.ntp\.org.*$' replace=""
  become: yes

- name: Ensure the Correct NTP Server is Set
  lineinfile: dest=/etc/chrony/chrony.conf regexp='^server .*$' state=present
              line="server {{ ntp }} iburst"
  notify: restart chrony
  become: yes

- name: Ensure the Controllers Can Serve Time to Other Nodes
  lineinfile: dest=/etc/chrony/chrony.conf regexp='^allow .*$' state=present
              line="allow all 10.2.1"
  notify: restart chrony
  become: yes
  when: inventory_hostname in groups['controllers']

- name: Ensure Apt Utilities are Installed
  apt: name=software-properties-common
  become: yes

- name: Ensure the Stein OpenStack Repository is Enabled
  shell: add-apt-repository cloud-archive:stein
  args:
    creates: /etc/apt/sources.list.d/cloudarchive-stein.list
  become: yes

- name: Ensure Package Cache is Current
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Ensure Latest Packages are Installed
  apt: upgrade=dist
  become: yes

- name: Ensure the OpenStack Client is Installed
  apt: name=python-openstackclient
  become: yes

- name: Ensure the Ceph Apt Key is Installed
  apt_key: url=https://download.ceph.com/keys/release.asc
  become: yes
  tags: ceph

- name: Ensure HTTPS Repositories are Enabled
  apt: name=apt-transport-https
  become: yes
  tags: ceph

- name: Ensure the Ceph Repository is Enabled
  apt_repository: repo='deb http://download.ceph.com/debian-mimic/ bionic main'
                  filename=ceph
  become: yes
  tags: ceph

- name: Ensure the Ceph Dependencies are Installed
  apt:
    name:
      - python3-rbd
      - python3-rados
      - ceph-common
  become: yes
  tags: ceph

- name: Ensure Open vSwitch is Installed
  apt: name="{{ item }}"
  with_items:
    - ovn-central
    - ovn-common
  become: yes
  when: inventory_hostname in groups['controllers'] or
        inventory_hostname in groups['compute']
  tags: neutron
