---

- name: Create the Hosts File
  lineinfile: dest=/etc/hosts  regexp="{{ hostvars[item][key]['ipv4']['address'] }}.*"
              line="{{ hostvars[item][key]['ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] }}"
  with_items: "{{ groups['all'] }}"
  become: yes
  vars:
    key: "ansible_{{ management_interface }}"

- name: Ensure the Second Loopback Address is Removed from the Hosts File
  lineinfile: dest=/etc/hosts  regexp="127.0.1.1.*" state=absent
  become: yes

- name: Ensure the Master Controller is in the Hosts File
  lineinfile: dest=/etc/hosts regexp="{{ master_controller_ip }}.*"
              line="{{ master_controller_ip }} {{ master_controller_hostname }}"
  become: yes
  tags: ha

- name: Ensure Chrony is Installed for NTP
  apt: name=chrony
  become: yes

- name: Ensure the the default NTP Servers are Removed
  replace: dest=/etc/chrony/chrony.conf
           regexp='^server .\.debian\.pool\.ntp\.org.*$' replace=""
  become: yes

- name: Ensure the Correct NTP Server is Set
  lineinfile: dest=/etc/chrony/chrony.conf regexp='^server .*$' state=present
              line="server {{ ntp }} iburst"
  notify: restart chrony
  become: yes

- name: Ensure Apt Utilities are Installed
  apt: name=software-properties-common
  become: yes

- name: Ensure the Newton OpenStack Repository is Enabled
  shell: add-apt-repository cloud-archive:newton
  become: yes

- name: Ensure Package Cache is Current
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Ensure Latest Packages are Installed
  apt: upgrade=dist
  become: yes

- name: Ensure the OpenStack Client is Installed
  apt: name=python-openstackclient
  become: yes

- name: Ensure the Ceph Apt Key is Installed
  apt_key: url=https://download.ceph.com/keys/release.asc
  become: yes
  tags: ceph

- name: Ensure HTTPS Repositories are Enabled
  apt: name=apt-transport-https
  become: yes
  tags: ceph

- name: Ensure the Ceph Repository is Enabled
  apt_repository: repo='deb https://download.ceph.com/debian-kraken/ xenial main'
                  filename=ceph
  become: yes
  tags: ceph
