---

nova_config:
  - { section: 'vnc', option: 'enabled', value: 'True' }
  - { section: 'vnc', option: 'vncserver_listen', value: '0.0.0.0' }
  - { section: 'vnc', option: 'vncserver_proxyclient_address', value: '$my_ip' }
  - { section: 'vnc', option: 'novncproxy_base_url',
      value: 'http://{{ master_controller_hostname }}:6080/vnc_auto.html' }
  - { section: 'glance', option: 'host', value: '{{ master_controller_hostname }}' }
  - { section: 'oslo_concurrency', option: 'lock_path', value: '/var/lib/nova/tmp' }

neutron_config:
  - { section: 'database', option: 'connection', value: ''}
