---

- name: restart mongodb
  service: name=mongodb state=restarted
  become: yes

- name: restart memcached
  service: name=memcached state=restarted
  become: yes

- name: sync keystone database
  shell: keystone-manage db_sync
  become: yes
  become_user: keystone

- name: initialize key repositories
  shell: keystone-manage {{ item }} --keystone-user keystone --keystone-group keystone
  become: yes
  with_items:
      - fernet_setup
      - credential_setup

- name: restart apache
  service: name=apache2 state=restarted
  become: yes

- name: sync glance database
  shell: glance-manage db_sync
  become: yes
  become_user: glance

- name: restart glance
  service: name={{ item }} state=restarted
  with_items:
    - glance-registry
    - glance-api
  become: yes

- name: restart nova
  service: name={{ item }} state=restarted
  with_items:
    - nova-api
    - nova-consoleauth
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy
  become: yes

- name: sync nova database
  shell: nova-manage {{ item }} sync
  become: yes
  become_user: nova
  with_items:
    - api_db
    - db

- name: sync neutron database
  shell: neutron-db-manage --config-file /etc/neutron/neutron.conf
         --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  become: yes
  become_user: neutron

- name: restart neutron
  service: name={{ item }} state=restarted
  with_items:
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
  become: yes

- name: restart nova api
  service: name=nova-api state=restarted
  become: yes
