---

- name: restart mongodb
  service: name=mongodb state=restarted
  become: yes

- name: sync keystone database
  keystone_manage: action=db_sync
  become: yes
  become_user: keystone

- name: restart apache
  service: name=apache2 state=restarted
  become: yes

- name: sync glance database
  shell: glance-manage db_sync
  become: yes
  become_user: glance

- name: restart glance
  service: name={{ item }} state=restarted
  with_items:
    - glance-registry
    - glance-api
  become: yes
