---

mq_user: "openstack"

nova_os_user: "nova"
neutron_os_user: "neutron"
cinder_os_user: "cinder"

admin_os_project: 'admin'
admin_os_user: 'admin'
default_os_user: 'acorn'
default_os_project: 'acorn'
service_os_project: 'service'

cinder_db_name: "cinder"
cinder_db_user: "cinder"

master_controller_hostname: "stack-master-controller"
master_controller_ip: "10.2.1.10"

public_network_options:
    cidr: "192.168.1.0/24"
    gateway: "192.168.1.254"
    dns: "192.168.1.254"
    start_ip: "192.168.1.211"
    end_ip: "192.168.1.219"

private_network_options:
    cidr: "10.0.1.0/24"
    gateway: "10.0.1.1"
    dns: "{{ public_network_options.dns }}"

management_network_cidr: "10.2.1.0/24"

rabbit_hosts:
    "{% for host in groups.controllers %}{{ mq_user }}:{{ vaulted_mq_password }}@{{ host }}{% if not loop.last %},{% endif %}{% endfor %}"

memcached_hosts:
    "{% for host in groups.controllers %}{{ host }}:11211{% if not loop.last %},{% endif %}{% endfor %}"


common_rabbit_config:
  - { section: 'DEFAULT', option: 'transport_url',
      value: 'rabbit://{{ rabbit_hosts }}' }

common_auth_config:
  - { section: 'keystone_authtoken', option: 'auth_uri',
      value: 'http://{{ master_controller_hostname }}:5000' }
  - { section: 'keystone_authtoken', option: 'auth_host',
      value: '{{ master_controller_ip }}' }
  - { section: 'keystone_authtoken', option: 'auth_url',
      value: 'http://{{ master_controller_hostname }}:35357' }
  - { section: 'keystone_authtoken', option: 'memcached_servers',
      value: '{{ memcached_hosts }}' }
  - { section: 'keystone_authtoken', option: 'auth_type', value: 'password' }
  - { section: 'keystone_authtoken', option: 'project_domain_id', value: 'default' }
  - { section: 'keystone_authtoken', option: 'user_domain_id', value: 'default' }
  - { section: 'keystone_authtoken', option: 'project_name',
      value: '{{ service_os_project }}' }

management_interface_key: "ansible_{{ management_interface }}"
management_ip: "{{ hostvars[ansible_hostname][management_interface_key].ipv4.address }}"


# Nova
common_nova_config:
  - { section: 'DEFAULT', option: 'auth_strategy', value: 'keystone' }
  - { section: 'keystone_authtoken', option: 'username',
      value: '{{ nova_os_user }}' }
  - { section: 'keystone_authtoken', option: 'password',
      value: '{{ vaulted_nova_os_password }}' }
  - { section: 'DEFAULT', option: 'my_ip', value: '{{ management_ip }}' }
  - { section: 'DEFAULT', option: 'use_neutron', value: 'True' }
  - { section: 'DEFAULT', option: 'firewall_driver',
      value: 'nova.virt.firewall.NoopFirewallDriver' }
  - { section: 'oslo_concurrency', option: 'lock_path',
      value: '/var/lib/nova/tmp' }

# Neutron
common_neutron_config:
  - { section: 'DEFAULT', option: 'core_plugin', value: 'ml2' }
  - { section: 'keystone_authtoken', option: 'username',
      value: '{{ neutron_os_user }}' }
  - { section: 'keystone_authtoken', option: 'password',
      value: '{{ vaulted_neutron_os_password }}' }

common_ovs_config:
  - { section: 'DEFAULT', option: 'enable_distributed_routing', value: 'True' }
  - { section: 'agent', option: 'l2_population', value: 'True' }
  - { section: 'agent', option: 'tunnel_types', value: 'vxlan' }
  - { section: 'ovs', option: 'bridge_mappings', value: 'provider:br-provider' }
  - { section: 'securitygroup', option: 'firewall_driver', value: 'openvswitch' }

common_l3_agent_config:
    - { option: 'interface_driver', value: 'openvswitch' }
    - { option: 'external_network_bridge', value: '' }

common_nova_neutron_config:
  - { option: 'url', value: 'http://{{ master_controller_hostname }}:9696' }
  - { option: 'auth_url', value: 'http://{{ master_controller_hostname }}:35357' }
  - { option: 'auth_type', value: 'password' }
  - { option: 'project_domain_id', value: 'default' }
  - { option: 'user_domain_id', value: 'default' }
  - { option: 'region_name', value: 'RegionOne' }
  - { option: 'project_name', value: '{{ service_os_project }}' }
  - { option: 'username', value: '{{ neutron_os_user }}' }
  - { option: 'password', value: '{{ vaulted_neutron_os_password }}' }
  - { option: 'service_metadata_proxy', value: 'True' }
  - { option: 'metadata_proxy_shared_secret', value: '{{ vaulted_metadata_secret }}' }

# Cinder
common_cinder_config:
  - { section: 'DEFAULT', option: 'my_ip', value: '{{ management_ip }}' }
  - { section: 'DEFAULT', option: 'glance_api_servers', value: '{{ master_controller_hostname }}:9292' }
  - { section: 'DEFAULT', option: 'glance_api_version', value: '2' }
  - { section: 'oslo_concurrency', option: 'lock_path', value: '/var/lib/cinder/tmp' }
  - { section: 'keystone_authtoken', option: 'username', value: '{{ cinder_os_user }}'}
  - { section: 'keystone_authtoken', option: 'password', value: '{{ vaulted_cinder_os_password }}'}
