---

keystone_db_name: "keystone"
keystone_db_user: "keystone"
glance_db_name: "glance"
glance_db_user: "glance"
glance_os_user: "glance"
nova_db_name: "nova"
nova_db_user: "nova"
neutron_db_name: "neutron"
neutron_db_user: "neutron"

glance_api_config:
  - { section: 'DEFAULT', option: 'show_image_direct_url', value: 'True' }
  - { section: 'glance_store', option: 'stores', value: 'rbd' }
  - { section: 'glance_store', option: 'default_store', value: 'rbd' }
  - { section: 'glance_store', option: 'rbd_store_pool', value: 'images' }
  - { section: 'glance_store', option: 'rbd_store_user', value: 'glance' }
  - { section: 'glance_store', option: 'rbd_store_ceph_conf', value: '/etc/ceph/ceph.conf' }
  - { section: 'glance_store', option: 'rbd_store_chunk_size', value: '8' }

glance_common_config:
  - { section: 'database', option: 'connection',
      value: 'postgresql://{{ glance_db_user }}:{{ vaulted_db_password }}@localhost/{{ glance_db_name }}' }
  - { section: 'keystone_authtoken', option: 'username', value: "{{ glance_os_user }}" }
  - { section: 'keystone_authtoken', option: 'password', value: "{{ vaulted_glance_os_password }}" }
  - { section: 'paste_deploy', option: 'flavor', value: 'keystone' }

nova_config:
  - { section: 'database', option: 'connection',
      value: 'postgresql://{{ nova_db_user }}:{{ vaulted_db_password }}@localhost/{{ nova_db_name }}' }
  - { section: 'api_database', option: 'connection',
      value: 'postgresql://{{ nova_db_user }}:{{ vaulted_db_password }}@localhost/{{ nova_db_name }}_api' }
  - { section: 'vnc', option: 'vncserver_listen', value: '$my_ip' }
  - { section: 'vnc', option: 'vncserver_proxyclient_address', value: '$my_ip' }
  - { section: 'glance', option: 'api_servers', value: '{{ ansible_hostname }}:9292' }
  - { section: 'libvirt', option: 'rbd_user', value: 'cinder' }
  - { section: 'libvirt', option: 'rbd_secret_uuid', value: '{{ vaulted_rbd_cinder_uuid }}' }

neutron_config:
  - { section: 'DEFAULT', option: 'verbose', value: 'True' }
  - { section: 'database', option: 'connection',
      value: 'postgresql://{{ neutron_db_user }}:{{ vaulted_db_password }}@localhost/{{ neutron_db_name }}' }
  - { section: 'DEFAULT', option: 'core_plugin', value: 'ml2' }
  - { section: 'DEFAULT', option: 'service_plugins', value: 'router' }
  - { section: 'DEFAULT', option: 'allow_overlapping_ips', value: 'True' }
  - { section: 'DEFAULT', option: 'notify_nova_on_port_status_changes',
      value: 'True'}
  - { section: 'DEFAULT', option: 'notify_nova_on_port_data_changes',
      value: 'True'}
  - { section: 'nova', option: 'auth_url',
      value: 'http://{{ master_controller_hostname }}:35357' }
  - { section: 'nova', option: 'auth_type', value: 'password' }
  - { section: 'nova', option: 'project_domain_id', value: 'default' }
  - { section: 'nova', option: 'user_domain_id', value: 'default' }
  - { section: 'nova', option: 'region_name', value: 'RegionOne' }
  - { section: 'nova', option: 'project_name',
      value: '{{ service_os_project }}' }
  - { section: 'nova', option: 'username',
      value: '{{ nova_os_user }}' }
  - { section: 'nova', option: 'password',
      value: '{{ vaulted_nova_os_password }}' }

cinder_config:
  - { section: 'DEFAULT', option: 'enabled_backends', value: 'ceph' }
  - { section: 'DEFAULT', option: 'glance_api_servers', value: '{{ master_controller_hostname }}:9292' }
  - { section: 'database', option: 'connection',
      value: 'postgresql://{{ cinder_db_user }}:{{ vaulted_db_password }}@{{ master_controller_hostname }}/{{ cinder_db_name }}' }
  - { section: 'ceph', option: 'volume_driver',
      value: 'cinder.volume.drivers.rbd.RBDDriver' }
  - { section: 'ceph', option: 'volume_backend_name', value: 'ceph' }
  - { section: 'ceph', option: 'rbd_pool', value: 'volumes' }
  - { section: 'ceph', option: 'rbd_ceph_conf', value: '/etc/ceph/ceph.conf' }
  - { section: 'ceph', option: 'rbd_flatten_volume_from_snapshot', value: 'false' }
  - { section: 'ceph', option: 'rbd_max_clone_depth', value: '5' }
  - { section: 'ceph', option: 'rbd_store_chunk_size', value: '4' }
  - { section: 'ceph', option: 'rados_connect_timeout', value: '-1' }
  - { section: 'ceph', option: 'glance_api_version', value: '2' }
  - { section: 'ceph', option: 'rbd_user', value: 'cinder' }
  - { section: 'ceph', option: 'rbd_secret_uuid', value: '{{ vaulted_rbd_cinder_uuid }}' }
