---

keystone_db_name: "keystone"
keystone_db_user: "keystone"
glance_db_name: "glance"
glance_db_user: "glance"
glance_os_user: "glance"
nova_db_name: "nova"
nova_db_user: "nova"
neutron_db_name: "neutron"
neutron_db_user: "neutron"
placement_db_name: "placement"
placement_db_user: "placement"

mysql_config:
  - { option: "bind-address", value: "{{ hostvars[ansible_hostname][key].ipv4.address }}" }
  - { option: "default-storage-engine", value: "innodb" }
  - { option: "innodb_file_per_table", value: "on" }
  - { option: "max_connections", value: "4096" }
  - { option: "collation-server", value: "utf8_general_ci" }
  - { option: "character-set-server", value: "utf8" }
    # Galera
  - { option: "datadir", value: "/var/lib/mysql"}
  - { option: "socket", value: "/var/run/mysqld/mysqld.sock"}
  - { option: "user", value: "mysql"}
  - { option: "binlog_format", value: "ROW"}
  - { option: "innodb_autoinc_lock_mode", value: "2"}
  - { option: "innodb_flush_log_at_trx_commit", value: "0"}
  - { option: "innodb_buffer_pool_size", value: "122M"}
  - { option: "wsrep_on", value: "ON" }
  - { option: "wsrep_provider", value: "/usr/lib/libgalera_smm.so"}
  - { option: "wsrep_provider_options", value: "'pc.recovery=TRUE;gcache.size=300M'"}
  - { option: "wsrep_cluster_name", value: "acorn_mysql_cluster"}
  - { option: "wsrep_cluster_address", value: "gcomm://{{ ip_list }}"}
  - { option: "wsrep_sst_method", value: "rsync"}
  - { option: "wsrep_node_name", value: "{{ ansible_hostname }}"}
  - { option: "wsrep_node_address", value: "{{ hostvars[ansible_hostname][key].ipv4.address }}"}

glance_api_config:
  - { section: 'DEFAULT', option: 'show_image_direct_url', value: 'True' }
  - { section: 'DEFAULT', option: 'enable_v1_api', value: 'False' }
  - { section: 'DEFAULT', option: 'enable_v2_api', value: 'True' }
  - { section: 'glance_store', option: 'stores', value: 'rbd' }
  - { section: 'glance_store', option: 'default_store', value: 'rbd' }
  - { section: 'glance_store', option: 'rbd_store_pool', value: 'images' }
  - { section: 'glance_store', option: 'rbd_store_user', value: 'glance' }
  - { section: 'glance_store', option: 'rbd_store_ceph_conf', value: '/etc/ceph/ceph.conf' }
  - { section: 'glance_store', option: 'rbd_store_chunk_size', value: '8' }

glance_common_config:
  - { section: 'DEFAULT', option: 'bind_host', value: '{{ management_ip }}' }
  - { section: 'database', option: 'connection',
      value: 'mysql+pymysql://{{ glance_db_user }}:{{ vaulted_db_password }}@{{ master_controller_hostname }}/{{ glance_db_name }}' }
  - { section: 'keystone_authtoken', option: 'username', value: "{{ glance_os_user }}" }
  - { section: 'keystone_authtoken', option: 'password', value: "{{ vaulted_glance_os_password }}" }
  - { section: 'paste_deploy', option: 'flavor', value: 'keystone' }

placement_config:
  - { section: 'api', option: 'auth_strategy', value: 'keystone' }
  - { section: 'placement_database', option: 'connection',
      value: 'mysql+pymysql://{{ placement_db_user }}:{{ vaulted_db_password }}@{{ master_controller_hostname }}/{{ placement_db_name }}' }
  - { section: 'keystone_authtoken', option: 'username', value: "{{ placement_os_user }}" }
  - { section: 'keystone_authtoken', option: 'password', value: "{{ vaulted_placement_os_password }}" }

nova_config:
  - { section: 'DEFAULT', option: 'osapi_compute_listen', value: '{{ management_ip }}' }
  - { section: 'DEFAULT', option: 'metadata_listen', value: '{{ management_ip }}' }
  - { section: 'database', option: 'connection',
      value: 'mysql+pymysql://{{ nova_db_user }}:{{ vaulted_db_password }}@{{ master_controller_hostname }}/{{ nova_db_name }}' }
  - { section: 'api_database', option: 'connection',
      value: 'mysql+pymysql://{{ nova_db_user }}:{{ vaulted_db_password }}@{{ master_controller_hostname }}/{{ nova_db_name }}_api' }
  - { section: 'vnc', option: 'novncproxy_host', value: '{{ management_ip }}' }
  - { section: 'vnc', option: 'vncserver_listen', value: '$my_ip' }
  - { section: 'vnc', option: 'vncserver_proxyclient_address', value: '$my_ip' }
  - { section: 'glance', option: 'api_servers', value: 'http://{{ master_controller_hostname }}:9292' }
  - { section: 'libvirt', option: 'rbd_user', value: 'cinder' }
  - { section: 'libvirt', option: 'rbd_secret_uuid', value: '{{ vaulted_rbd_cinder_uuid }}' }
  - { section: 'scheduler', option: 'discover_hosts_in_cells_interval', value: '300' }

neutron_config:
  - { section: 'DEFAULT', option: 'bind_host', value: '{{ management_ip }}' }
  - { section: 'database', option: 'connection',
      value: 'mysql+pymysql://{{ neutron_db_user }}:{{ vaulted_db_password }}@{{ master_controller_hostname }}/{{ neutron_db_name }}' }
  - { section: 'DEFAULT', option: 'service_plugins', value: 'router' }
  - { section: 'DEFAULT', option: 'allow_overlapping_ips', value: 'True' }
  - { section: 'DEFAULT', option: 'notify_nova_on_port_status_changes',
      value: 'True'}
  - { section: 'DEFAULT', option: 'notify_nova_on_port_data_changes',
      value: 'True'}
  - { section: 'DEFAULT', option: 'l3_ha', value: 'True'}
  - { section: 'DEFAULT', option: 'allow_automatic_l3agent_failover', value: 'True'}
  - { section: 'DEFAULT', option: 'max_l3_agents_per_router', value: '5'}
  - { section: 'DEFAULT', option: 'router_distributed', value: 'True' }
  - { section: 'nova', option: 'auth_url', value: 'http://{{ master_controller_hostname }}:35357' }
  - { section: 'nova', option: 'auth_type', value: 'password' }
  - { section: 'nova', option: 'project_domain_id', value: 'default' }
  - { section: 'nova', option: 'user_domain_id', value: 'default' }
  - { section: 'nova', option: 'region_name', value: 'RegionOne' }
  - { section: 'nova', option: 'project_name', value: '{{ service_os_project }}' }
  - { section: 'nova', option: 'username', value: '{{ nova_os_user }}' }
  - { section: 'nova', option: 'password', value: '{{ vaulted_nova_os_password }}' }
  - { section: 'agent', option: 'dhcp_agents_per_network', value: '3' }

ml2_config:
  - { section: 'ml2', option: 'type_drivers', value: 'flat,vlan,vxlan' }
  - { section: 'ml2', option: 'tenant_network_types', value: 'vxlan' }
  - { section: 'ml2', option: 'mechanism_drivers', value: 'openvswitch,l2population' }
  - { section: 'ml2', option: 'extension_drivers', value: 'port_security' }
  - { section: 'ml2_type_flat', option: 'flat_networks', value: 'provider' }
  - { section: 'ml2_type_vlan', option: 'network_vlan_ranges', value: 'provider' }
  - { section: 'ml2_type_vxlan', option: 'vni_ranges', value: '500:1500' }
  - { section: 'securitygroup', option: 'firewall_driver', value: 'openvswitch' }

ovs_agent_config:
  - { section: 'ovs', option: 'local_ip', value: '{{ hostvars[ansible_hostname]["ansible_" + overlay_interface].ipv4.address }}' }

l3_agent_config:
    - { option: 'agent_mode', value: 'dvr_snat' }

cinder_config:
  - { section: 'DEFAULT', option: 'host', value: '{{ master_controller_hostname }}' }
  - { section: 'DEFAULT', option: 'osapi_volume_listen', value: '{{ management_ip }}' }
  - { section: 'DEFAULT', option: 'enabled_backends', value: 'ceph' }
  - { section: 'database', option: 'connection',
      value: 'mysql+pymysql://{{ cinder_db_user }}:{{ vaulted_db_password }}@{{ master_controller_hostname }}/{{ cinder_db_name }}' }
  - { section: 'ceph', option: 'volume_driver',
      value: 'cinder.volume.drivers.rbd.RBDDriver' }
  - { section: 'ceph', option: 'volume_backend_name', value: 'ceph' }
  - { section: 'ceph', option: 'rbd_pool', value: 'volumes' }
  - { section: 'ceph', option: 'rbd_ceph_conf', value: '/etc/ceph/ceph.conf' }
  - { section: 'ceph', option: 'rbd_flatten_volume_from_snapshot', value: 'false' }
  - { section: 'ceph', option: 'rbd_max_clone_depth', value: '5' }
  - { section: 'ceph', option: 'rbd_store_chunk_size', value: '4' }
  - { section: 'ceph', option: 'rados_connect_timeout', value: '-1' }
  - { section: 'ceph', option: 'glance_api_version', value: '2' }
  - { section: 'ceph', option: 'rbd_user', value: 'cinder' }
  - { section: 'ceph', option: 'rbd_secret_uuid', value: '{{ vaulted_rbd_cinder_uuid }}' }
