---

keystone_db_name: "keystone"
keystone_db_user: "keystone"
glance_db_name: "glance"
glance_db_user: "glance"
glance_os_user: "glance"
nova_db_name: "nova"
nova_db_user: "nova"
neutron_db_name: "neutron"
neutron_db_user: "neutron"

glance_api_config:
  - { section: 'glance_store', option: 'stores', value: 'file,http' }
  - { section: 'glance_store', option: 'default_store', value: 'file' }
  - { section: 'glance_store', option: 'filesystem_store_datadir', value: '/var/lib/glance/images/' }

glance_common_config:
  - { section: 'database', option: 'connection',
      value: 'postgresql://{{ glance_db_user }}:{{ vaulted_db_password }}@localhost/{{ glance_db_name }}' }
  - { section: 'keystone_authtoken', option: 'username', value: "{{ glance_os_user }}" }
  - { section: 'keystone_authtoken', option: 'password', value: "{{ vaulted_glance_os_password }}" }
  - { section: 'paste_deploy', option: 'flavor', value: 'keystone' }

nova_config:
  - { section: 'database', option: 'connection',
      value: 'postgresql://{{ nova_db_user }}:{{ vaulted_db_password }}@localhost/{{ nova_db_name }}' }
  - { section: 'api_database', option: 'connection',
      value: 'postgresql://{{ nova_db_user }}:{{ vaulted_db_password }}@localhost/{{ nova_db_name }}_api' }
  - { section: 'vnc', option: 'vncserver_listen', value: '$my_ip' }
  - { section: 'vnc', option: 'vncserver_proxyclient_address', value: '$my_ip' }
  - { section: 'glance', option: 'api_servers', value: 'http://{{ ansible_hostname }}:9292' }

neutron_config:
  - { section: 'DEFAULT', option: 'verbose', value: 'True' }
  - { section: 'database', option: 'connection',
      value: 'postgresql://{{ neutron_db_user }}:{{ vaulted_db_password }}@localhost/{{ neutron_db_name }}' }
  - { section: 'DEFAULT', option: 'core_plugin', value: 'ml2' }
  - { section: 'DEFAULT', option: 'service_plugins', value: 'router' }
  - { section: 'DEFAULT', option: 'allow_overlapping_ips', value: 'True' }
  - { section: 'DEFAULT', option: 'notify_nova_on_port_status_changes',
      value: 'True'}
  - { section: 'DEFAULT', option: 'notify_nova_on_port_data_changes',
      value: 'True'}
  - { section: 'nova', option: 'auth_url',
      value: 'http://{{ master_controller_hostname }}:35357' }
  - { section: 'nova', option: 'auth_type', value: 'password' }
  - { section: 'nova', option: 'project_domain_id', value: 'default' }
  - { section: 'nova', option: 'user_domain_id', value: 'default' }
  - { section: 'nova', option: 'region_name', value: 'RegionOne' }
  - { section: 'nova', option: 'project_name',
      value: '{{ service_os_project }}' }
  - { section: 'nova', option: 'username',
      value: '{{ nova_os_user }}' }
  - { section: 'nova', option: 'password',
      value: '{{ vaulted_nova_os_password }}' }
