---

- name: restart nova compute
  service: name=nova-compute state=restarted
  become: yes

- name: restart ovs agent
  service: name=neutron-openvswitch-agent state=restarted
  become: yes

- name: restart dhcp agent
  service: name=neutron-dhcp-agent state=restarted
  become: yes

- name: restart metadata agent
  service: name=neutron-metadata-agent state=restarted
  become: yes

- name: restart l3 agent
  service: name=neutron-l3-agent state=restarted
  become: yes
